version: '3.8'

services:
  app:
    container_name: ${APP_NAME:-react-scenario-lab}
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "${HOST_PORT:-8002}:${CONTAINER_PORT:-3000}"
    environment:
      - NODE_ENV=${NODE_ENV:-production}
      - CONTAINER_PORT=${CONTAINER_PORT:-3000}
      - HOSTNAME=${HOSTNAME:-0.0.0.0}
      - NEXT_TELEMETRY_DISABLED=${NEXT_TELEMETRY_DISABLED:-1}
      - UPLOAD_BASE_DIR=${UPLOAD_BASE_DIR:-/app/uploads}
      - TEMP_BASE_DIR=${TEMP_BASE_DIR:-/app/temp}
    env_file:
      - .env
    volumes:
      - ./uploads:/app/uploads
      - ./temp:/app/temp
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:${CONTAINER_PORT:-3000}/"]
      interval: ${HEALTH_CHECK_INTERVAL:-30s}
      timeout: ${HEALTH_CHECK_TIMEOUT:-10s}
      retries: ${HEALTH_CHECK_RETRIES:-3}
      start_period: ${HEALTH_CHECK_START_PERIOD:-20s}
    networks:
      - app-network

networks:
  app-network:
    driver: bridge